item {
  id: 0
  name: 'Haemorhous cassinii'
}
item {
  id: 1
  name: 'Aramus guarauna'
}
item {
  id: 2
  name: 'Rupornis magnirostris'
}
item {
  id: 3
  name: 'Cyanocitta cristata'
}
item {
  id: 4
  name: 'Cyanocitta stelleri'
}
item {
  id: 5
  name: 'Balearica regulorum'
}
item {
  id: 6
  name: 'Pyrocephalus rubinus'
}
item {
  id: 7
  name: 'Recurvirostra americana'
}
item {
  id: 8
  name: 'Ardeotis kori'
}
item {
  id: 9
  name: 'Pica nuttalli'
}
item {
  id: 10
  name: 'Perisoreus canadensis'
}
item {
  id: 11
  name: 'Antigone canadensis'
}
item {
  id: 12
  name: 'Parkesia noveboracensis'
}
item {
  id: 13
  name: 'Ardea herodias occidentalis'
}
item {
  id: 14
  name: 'Porzana carolina'
}
item {
  id: 15
  name: 'Anas platyrhynchos diazi'
}
item {
  id: 16
  name: 'Motacilla cinerea'
}
item {
  id: 17
  name: 'Empidonax difficilis'
}
item {
  id: 18
  name: 'Empidonax minimus'
}
item {
  id: 19
  name: 'Empidonax fulvifrons'
}
item {
  id: 20
  name: 'Empidonax traillii'
}
item {
  id: 21
  name: 'Empidonax hammondii'
}
item {
  id: 22
  name: 'Empidonax occidentalis'
}
item {
  id: 23
  name: 'Rallus limicola'
}
item {
  id: 24
  name: 'Grus grus'
}
item {
  id: 25
  name: 'Quiscalus major'
}
item {
  id: 26
  name: 'Branta leucopsis'
}
item {
  id: 27
  name: 'Cyanocorax yucatanicus'
}
item {
  id: 28
  name: 'Cyanocorax yncas'
}
item {
  id: 29
  name: 'Oceanites oceanicus'
}
item {
  id: 30
  name: 'Quiscalus niger'
}
item {
  id: 31
  name: 'Psilorhinus morio'
}
item {
  id: 32
  name: 'Megarynchus pitangua'
}
item {
  id: 33
  name: 'Gallinula tenebrosa'
}
item {
  id: 34
  name: 'Gallus gallus domesticus'
}
item {
  id: 35
  name: 'Numida meleagris'
}
item {
  id: 36
  name: 'Junco hyemalis caniceps'
}
item {
  id: 37
  name: 'Tyrannus vociferans'
}
item {
  id: 38
  name: 'Tyrannus tyrannus'
}
item {
  id: 39
  name: 'Tyrannus forficatus'
}
item {
  id: 40
  name: 'Tyrannus crassirostris'
}
item {
  id: 41
  name: 'Tyrannus verticalis'
}
item {
  id: 42
  name: 'Tyrannus savana'
}
item {
  id: 43
  name: 'Gallirallus australis'
}
item {
  id: 44
  name: 'Calocitta formosa'
}
item {
  id: 45
  name: 'Calocitta colliei'
}
item {
  id: 46
  name: 'Fulica americana'
}
item {
  id: 47
  name: 'Pachyramphus aglaiae'
}
item {
  id: 48
  name: 'Buteo lagopus'
}
item {
  id: 49
  name: 'Cygnus atratus'
}
item {
  id: 50
  name: 'Philesturnus rufusater'
}
item {
  id: 51
  name: 'Larus marinus'
}
item {
  id: 52
  name: 'Pitangus sulphuratus'
}
item {
  id: 53
  name: 'Anas rubripes'
}
item {
  id: 54
  name: 'Anthus novaeseelandiae novaeseelandiae'
}
item {
  id: 55
  name: 'Sayornis phoebe'
}
item {
  id: 56
  name: 'Sayornis nigricans'
}
item {
  id: 57
  name: 'Tityra semifasciata'
}
item {
  id: 58
  name: 'Dryocopus lineatus'
}
item {
  id: 59
  name: 'Porphyrio melanotus'
}
item {
  id: 60
  name: 'Anas bahamensis'
}
item {
  id: 61
  name: 'Egretta novaehollandiae'
}
item {
  id: 62
  name: 'Anas crecca carolinensis'
}
item {
  id: 63
  name: 'Alectoris chukar'
}
item {
  id: 64
  name: 'Tachybaptus dominicus'
}
item {
  id: 65
  name: 'Artemisiospiza belli'
}
item {
  id: 66
  name: 'Gallus gallus'
}
item {
  id: 67
  name: 'Cardinalis sinuatus'
}
item {
  id: 68
  name: 'Cardinalis cardinalis'
}
item {
  id: 69
  name: 'Melospiza lincolnii'
}
item {
  id: 70
  name: 'Podilymbus podiceps'
}
item {
  id: 71
  name: 'Melospiza georgiana'
}
item {
  id: 72
  name: 'Meleagris gallopavo'
}
item {
  id: 73
  name: 'Meleagris ocellata'
}
item {
  id: 74
  name: 'Lagopus lagopus'
}
item {
  id: 75
  name: 'Spizella atrogularis'
}
item {
  id: 76
  name: 'Pyrrhocorax graculus'
}
item {
  id: 77
  name: 'Spizella breweri'
}
item {
  id: 78
  name: 'Sialia currucoides'
}
item {
  id: 79
  name: 'Spizella pusilla'
}
item {
  id: 80
  name: 'Anas superciliosa'
}
item {
  id: 81
  name: 'Passerella iliaca'
}
item {
  id: 82
  name: 'Phoenicopterus ruber'
}
item {
  id: 83
  name: 'Sylvia atricapilla'
}
item {
  id: 84
  name: 'Vireo bellii'
}
item {
  id: 85
  name: 'Vireo plumbeus'
}
item {
  id: 86
  name: 'Vireo philadelphicus'
}
item {
  id: 87
  name: 'Vireo flavifrons'
}
item {
  id: 88
  name: 'Vireo olivaceus'
}
item {
  id: 89
  name: 'Zonotrichia querula'
}
item {
  id: 90
  name: 'Vireo huttoni'
}
item {
  id: 91
  name: 'Zonotrichia albicollis'
}
item {
  id: 92
  name: 'Zonotrichia atricapilla'
}
item {
  id: 93
  name: 'Emberiza citrinella'
}
item {
  id: 94
  name: 'Bucephala islandica'
}
item {
  id: 95
  name: 'Emberiza schoeniclus'
}
item {
  id: 96
  name: 'Vireo gilvus'
}
item {
  id: 97
  name: 'Serinus serinus'
}
item {
  id: 98
  name: 'Serinus mozambicus'
}
item {
  id: 99
  name: 'Lophura leucomelanos'
}
item {
  id: 100
  name: 'Euphonia elegantissima'
}
item {
  id: 101
  name: 'Euphonia hirundinacea'
}
item {
  id: 102
  name: 'Euphonia affinis'
}
item {
  id: 103
  name: 'Agelaius tricolor'
}
item {
  id: 104
  name: 'Momotus lessonii'
}
item {
  id: 105
  name: 'Zosterops japonicus'
}
item {
  id: 106
  name: 'Phalacrocorax pelagicus'
}
item {
  id: 107
  name: 'Icterus cucullatus'
}
item {
  id: 108
  name: 'Icterus graduacauda'
}
item {
  id: 109
  name: 'Motacilla aguimp'
}
item {
  id: 110
  name: 'Anas superciliosa × platyrhynchos'
}
item {
  id: 111
  name: 'Icterus pustulatus'
}
item {
  id: 112
  name: 'Icterus gularis'
}
item {
  id: 113
  name: 'Carduelis cannabina'
}
item {
  id: 114
  name: 'Catharus minimus'
}
item {
  id: 115
  name: 'Amaurornis phoenicurus'
}
item {
  id: 116
  name: 'Pavo cristatus'
}
item {
  id: 117
  name: 'Rallus crepitans'
}
item {
  id: 118
  name: 'Nestor meridionalis septentrionalis'
}
item {
  id: 119
  name: 'Pipilo chlorurus'
}
item {
  id: 120
  name: 'Pipilo maculatus'
}
item {
  id: 121
  name: 'Pipilo erythrophthalmus'
}
item {
  id: 122
  name: 'Cairina moschata domestica'
}
item {
  id: 123
  name: 'Phalacrocorax varius'
}
item {
  id: 124
  name: 'Picoides dorsalis'
}
item {
  id: 125
  name: 'Picoides nuttallii'
}
item {
  id: 126
  name: 'Picoides scalaris'
}
item {
  id: 127
  name: 'Callipepla gambelii'
}
item {
  id: 128
  name: 'Pyrrhula pyrrhula'
}
item {
  id: 129
  name: 'Phalacrocorax brasilianus'
}
item {
  id: 130
  name: 'Picoides pubescens'
}
item {
  id: 131
  name: 'Colinus virginianus'
}
item {
  id: 132
  name: 'Sporophila torqueola'
}
item {
  id: 133
  name: 'Picoides villosus'
}
item {
  id: 134
  name: 'Calidris pusilla'
}
item {
  id: 135
  name: 'Picoides arcticus'
}
item {
  id: 136
  name: 'Aythya marila'
}
item {
  id: 137
  name: 'Phaethon aethereus'
}
item {
  id: 138
  name: 'Sturnella magna'
}
item {
  id: 139
  name: 'Melopsittacus undulatus'
}
item {
  id: 140
  name: 'Aythya affinis'
}
item {
  id: 141
  name: 'Aythya novaeseelandiae'
}
item {
  id: 142
  name: 'Cyrtonyx montezumae'
}
item {
  id: 143
  name: 'Pelecanus occidentalis'
}
item {
  id: 144
  name: 'Cinclus cinclus'
}
item {
  id: 145
  name: 'Chen rossii'
}
item {
  id: 146
  name: 'Callipepla californica'
}
item {
  id: 147
  name: 'Quiscalus quiscula'
}
item {
  id: 148
  name: 'Quiscalus mexicanus'
}
item {
  id: 149
  name: 'Callipepla squamata'
}
item {
  id: 150
  name: 'Dryocopus pileatus'
}
item {
  id: 151
  name: 'Passerina caerulea'
}
item {
  id: 152
  name: 'Amazilia beryllina'
}
item {
  id: 153
  name: 'Geothlypis trichas'
}
item {
  id: 154
  name: 'Trogon melanocephalus'
}
item {
  id: 155
  name: 'Sylvia communis'
}
item {
  id: 156
  name: 'Pinicola enucleator'
}
item {
  id: 157
  name: 'Coccothraustes vespertinus'
}
item {
  id: 158
  name: 'Coccothraustes coccothraustes'
}
item {
  id: 159
  name: 'Vermivora chrysoptera'
}
item {
  id: 160
  name: 'Opisthocomus hoazin'
}
item {
  id: 161
  name: 'Setophaga coronata coronata'
}
item {
  id: 162
  name: 'Diglossa baritula'
}
item {
  id: 163
  name: 'Saltator coerulescens'
}
item {
  id: 164
  name: 'Saltator atriceps'
}
item {
  id: 165
  name: 'Sicalis flaveola'
}
item {
  id: 166
  name: 'Aix galericulata'
}
item {
  id: 167
  name: 'Junco hyemalis hyemalis'
}
item {
  id: 168
  name: 'Eupsittula canicularis'
}
item {
  id: 169
  name: 'Microcarbo melanoleucos'
}
item {
  id: 170
  name: 'Piranga rubra'
}
item {
  id: 171
  name: 'Piranga olivacea'
}
item {
  id: 172
  name: 'Piranga flava'
}
item {
  id: 173
  name: 'Amphispiza bilineata'
}
item {
  id: 174
  name: 'Larus dominicanus'
}
item {
  id: 175
  name: 'Piaya cayana'
}
item {
  id: 176
  name: 'Aimophila ruficeps'
}
item {
  id: 177
  name: 'Melanerpes lewis'
}
item {
  id: 178
  name: 'Melanerpes uropygialis'
}
item {
  id: 179
  name: 'Passerculus sandwichensis'
}
item {
  id: 180
  name: 'Melanerpes pucherani'
}
item {
  id: 181
  name: 'Salpinctes obsoletus'
}
item {
  id: 182
  name: 'Melanerpes carolinus'
}
item {
  id: 183
  name: 'Melanerpes chrysogenys'
}
item {
  id: 184
  name: 'Melanerpes formicivorus'
}
item {
  id: 185
  name: 'Colaptes auratus'
}
item {
  id: 186
  name: 'Basileuterus rufifrons'
}
item {
  id: 187
  name: 'Larus michahellis'
}
item {
  id: 188
  name: 'Ramphocelus passerinii'
}
item {
  id: 189
  name: 'Athene cunicularia'
}
item {
  id: 190
  name: 'Branta hutchinsii'
}
item {
  id: 191
  name: 'Fringilla montifringilla'
}
item {
  id: 192
  name: 'Fringilla coelebs'
}
item {
  id: 193
  name: 'Junco hyemalis'
}
item {
  id: 194
  name: 'Cuculus canorus'
}
item {
  id: 195
  name: 'Junco phaeonotus'
}
item {
  id: 196
  name: 'Ammodramus nelsoni'
}
item {
  id: 197
  name: 'Ammodramus savannarum'
}
item {
  id: 198
  name: 'Ammodramus maritimus'
}
item {
  id: 199
  name: 'Coccyzus erythropthalmus'
}
item {
  id: 200
  name: 'Coccyzus minor'
}
item {
  id: 201
  name: 'Coccyzus americanus'
}
item {
  id: 202
  name: 'Nucifraga columbiana'
}
item {
  id: 203
  name: 'Crotophaga sulcirostris'
}
item {
  id: 204
  name: 'Pooecetes gramineus'
}
item {
  id: 205
  name: 'Arremonops rufivirgatus'
}
item {
  id: 206
  name: 'Geococcyx californianus'
}
item {
  id: 207
  name: 'Geococcyx velox'
}
item {
  id: 208
  name: 'Coereba flaveola'
}
item {
  id: 209
  name: 'Passerina ciris'
}
item {
  id: 210
  name: 'Alectura lathami'
}
item {
  id: 211
  name: 'Passerina leclancherii'
}
item {
  id: 212
  name: 'Passerina amoena'
}
item {
  id: 213
  name: 'Icteria virens'
}
item {
  id: 214
  name: 'Crax rubra'
}
item {
  id: 215
  name: 'Penelope purpurascens'
}
item {
  id: 216
  name: 'Copsychus malabaricus'
}
item {
  id: 217
  name: 'Paroaria capitata'
}
item {
  id: 218
  name: 'Cyanerpes cyaneus'
}
item {
  id: 219
  name: 'Microcarbo melanoleucos brevirostris'
}
item {
  id: 220
  name: 'Sphyrapicus thyroideus'
}
item {
  id: 221
  name: 'Pheucticus ludovicianus'
}
item {
  id: 222
  name: 'Sphyrapicus ruber'
}
item {
  id: 223
  name: 'Pheucticus melanocephalus'
}
item {
  id: 224
  name: 'Sphyrapicus nuchalis'
}
item {
  id: 225
  name: 'Ortalis poliocephala'
}
item {
  id: 226
  name: 'Ortalis vetula'
}
item {
  id: 227
  name: 'Corvus albus'
}
item {
  id: 228
  name: 'Mniotilta varia'
}
item {
  id: 229
  name: 'Volatinia jacarina'
}
item {
  id: 230
  name: 'Thraupis palmarum'
}
item {
  id: 231
  name: 'Momotus mexicanus'
}
item {
  id: 232
  name: 'Euphagus cyanocephalus'
}
item {
  id: 233
  name: 'Cacatua galerita'
}
item {
  id: 234
  name: 'Junco hyemalis oreganus'
}
item {
  id: 235
  name: 'Pluvialis fulva'
}
item {
  id: 236
  name: 'Molothrus aeneus'
}
item {
  id: 237
  name: 'Molothrus ater'
}
item {
  id: 238
  name: 'Merops pusillus'
}
item {
  id: 239
  name: 'Merops apiaster'
}
item {
  id: 240
  name: 'Pteroglossus torquatus'
}
item {
  id: 241
  name: 'Loxia curvirostra'
}
item {
  id: 242
  name: 'Merops orientalis'
}
item {
  id: 243
  name: 'Loxia leucoptera'
}
item {
  id: 244
  name: 'Coracias garrulus'
}
item {
  id: 245
  name: 'Coracias caudatus'
}
item {
  id: 246
  name: 'Coracias benghalensis'
}
item {
  id: 247
  name: 'Xanthocephalus xanthocephalus'
}
item {
  id: 248
  name: 'Chondestes grammacus'
}
item {
  id: 249
  name: 'Dolichonyx oryzivorus'
}
item {
  id: 250
  name: 'Pandion haliaetus'
}
item {
  id: 251
  name: 'Phainopepla nitens'
}
item {
  id: 252
  name: 'Tyrannus couchii'
}
item {
  id: 253
  name: 'Phylloscopus collybita'
}
item {
  id: 254
  name: 'Circus cyaneus hudsonius'
}
item {
  id: 255
  name: 'Grallina cyanoleuca'
}
item {
  id: 256
  name: 'Plectrophenax nivalis'
}
item {
  id: 257
  name: 'Calamospiza melanocorys'
}
item {
  id: 258
  name: 'Regulus calendula'
}
item {
  id: 259
  name: 'Regulus ignicapilla'
}
item {
  id: 260
  name: 'Regulus regulus'
}
item {
  id: 261
  name: 'Regulus satrapa'
}
item {
  id: 262
  name: 'Tyrannus melancholicus'
}
item {
  id: 263
  name: 'Pelecanus conspicillatus'
}
item {
  id: 264
  name: 'Aulacorhynchus prasinus'
}
item {
  id: 265
  name: 'Todiramphus sanctus'
}
item {
  id: 266
  name: 'Icterus bullockii'
}
item {
  id: 267
  name: 'Spiza americana'
}
item {
  id: 268
  name: 'Tyrannus dominicensis'
}
item {
  id: 269
  name: 'Chlidonias niger'
}
item {
  id: 270
  name: 'Oriturus superciliosus'
}
item {
  id: 271
  name: 'Psarocolius montezuma'
}
item {
  id: 272
  name: 'Turdus pilaris'
}
item {
  id: 273
  name: 'Notiomystis cincta'
}
item {
  id: 274
  name: 'Sagittarius serpentarius'
}
item {
  id: 275
  name: 'Psittacula krameri'
}
item {
  id: 276
  name: 'Platycercus eximius'
}
item {
  id: 277
  name: 'Protonotaria citrea'
}
item {
  id: 278
  name: 'Megaceryle torquata'
}
item {
  id: 279
  name: 'Nestor meridionalis'
}
item {
  id: 280
  name: 'Amazona viridigenalis'
}
item {
  id: 281
  name: 'Amazona albifrons'
}
item {
  id: 282
  name: 'Amazona oratrix'
}
item {
  id: 283
  name: 'Saxicola rubetra'
}
item {
  id: 284
  name: 'Ara militaris'
}
item {
  id: 285
  name: 'Spizelloides arborea'
}
item {
  id: 286
  name: 'Ceryle rudis'
}
item {
  id: 287
  name: 'Chloroceryle aenea'
}
item {
  id: 288
  name: 'Chloroceryle amazona'
}
item {
  id: 289
  name: 'Myiozetetes similis'
}
item {
  id: 290
  name: 'Toxostoma curvirostre'
}
item {
  id: 291
  name: 'Megaceryle alcyon'
}
item {
  id: 292
  name: 'Eremophila alpestris'
}
item {
  id: 293
  name: 'Alisterus scapularis'
}
item {
  id: 294
  name: 'Cinnyris jugularis'
}
item {
  id: 295
  name: 'Xiphorhynchus flavigaster'
}
item {
  id: 296
  name: 'Jacana jacana'
}
item {
  id: 297
  name: 'Phalaropus fulicarius'
}
item {
  id: 298
  name: 'Streptopelia turtur'
}
item {
  id: 299
  name: 'Pica hudsonia'
}
item {
  id: 300
  name: 'Corvus cornix'
}
item {
  id: 301
  name: 'Myiopsitta monachus'
}
item {
  id: 302
  name: 'Streptopelia decaocto'
}
item {
  id: 303
  name: 'Piranga ludoviciana'
}
item {
  id: 304
  name: 'Ixobrychus exilis'
}
item {
  id: 305
  name: 'Auriparus flaviceps'
}
item {
  id: 306
  name: 'Geothlypis tolmiei'
}
item {
  id: 307
  name: 'Columba livia'
}
item {
  id: 308
  name: 'Setophaga citrina'
}
item {
  id: 309
  name: 'Setophaga cerulea'
}
item {
  id: 310
  name: 'Columba palumbus'
}
item {
  id: 311
  name: 'Piranga bidentata'
}
item {
  id: 312
  name: 'Patagioenas leucocephala'
}
item {
  id: 313
  name: 'Patagioenas fasciata'
}
item {
  id: 314
  name: 'Patagioenas flavirostris'
}
item {
  id: 315
  name: 'Setophaga discolor'
}
item {
  id: 316
  name: 'Chordeiles minor'
}
item {
  id: 317
  name: 'Chordeiles acutipennis'
}
item {
  id: 318
  name: 'Platalea leucorodia'
}
item {
  id: 319
  name: 'Phalaenoptilus nuttallii'
}
item {
  id: 320
  name: 'Haemorhous mexicanus'
}
item {
  id: 321
  name: 'Haemorhous purpureus'
}
item {
  id: 322
  name: 'Nyctidromus albicollis'
}
item {
  id: 323
  name: 'Campephilus guatemalensis'
}
item {
  id: 324
  name: 'Toxostoma rufum'
}
item {
  id: 325
  name: 'Leptotila verreauxi'
}
item {
  id: 326
  name: 'Nyctibius jamaicensis'
}
item {
  id: 327
  name: 'Anas penelope'
}
item {
  id: 328
  name: 'Buteo plagiatus'
}
item {
  id: 329
  name: 'Selasphorus calliope'
}
item {
  id: 330
  name: 'Megascops kennicottii'
}
item {
  id: 331
  name: 'Porphyrio poliocephalus'
}
item {
  id: 332
  name: 'Megascops asio'
}
item {
  id: 333
  name: 'Zenaida auriculata'
}
item {
  id: 334
  name: 'Hymenolaimus malacorhynchos'
}
item {
  id: 335
  name: 'Setophaga caerulescens'
}
item {
  id: 336
  name: 'Camptostoma imberbe'
}
item {
  id: 337
  name: 'Caracara plancus'
}
item {
  id: 338
  name: 'Columbina passerina'
}
item {
  id: 339
  name: 'Eupsittula nana'
}
item {
  id: 340
  name: 'Nestor notabilis'
}
item {
  id: 341
  name: 'Columbina talpacoti'
}
item {
  id: 342
  name: 'Geopelia striata'
}
item {
  id: 343
  name: 'Athene noctua'
}
item {
  id: 344
  name: 'Crotophaga ani'
}
item {
  id: 345
  name: 'Sialia sialis'
}
item {
  id: 346
  name: 'Platalea alba'
}
item {
  id: 347
  name: 'Bubo virginianus'
}
item {
  id: 348
  name: 'Petrochelidon fulva'
}
item {
  id: 349
  name: 'Progne subis'
}
item {
  id: 350
  name: 'Setophaga coronata auduboni'
}
item {
  id: 351
  name: 'Hirundo neoxena'
}
item {
  id: 352
  name: 'Hirundo rustica'
}
item {
  id: 353
  name: 'Calidris virgata'
}
item {
  id: 354
  name: 'Calidris pugnax'
}
item {
  id: 355
  name: 'Platalea regia'
}
item {
  id: 356
  name: 'Tachycineta thalassina'
}
item {
  id: 357
  name: 'Bostrychia hagedash'
}
item {
  id: 358
  name: 'Riparia riparia'
}
item {
  id: 359
  name: 'Eudocimus albus'
}
item {
  id: 360
  name: 'Plegadis falcinellus'
}
item {
  id: 361
  name: 'Plegadis chihi'
}
item {
  id: 362
  name: 'Corvus corax'
}
item {
  id: 363
  name: 'Stelgidopteryx serripennis'
}
item {
  id: 364
  name: 'Sula dactylatra'
}
item {
  id: 365
  name: 'Sula sula'
}
item {
  id: 366
  name: 'Sula leucogaster'
}
item {
  id: 367
  name: 'Morus serrator'
}
item {
  id: 368
  name: 'Eudyptula minor'
}
item {
  id: 369
  name: 'Megadyptes antipodes'
}
item {
  id: 370
  name: 'Scopus umbretta'
}
item {
  id: 371
  name: 'Troglodytes troglodytes'
}
item {
  id: 372
  name: 'Calidris canutus'
}
item {
  id: 373
  name: 'Lanius collurio'
}
item {
  id: 374
  name: 'Calidris bairdii'
}
item {
  id: 375
  name: 'Meleagris gallopavo intermedia'
}
item {
  id: 376
  name: 'Calidris mauri'
}
item {
  id: 377
  name: 'Calidris maritima'
}
item {
  id: 378
  name: 'Calidris alpina'
}
item {
  id: 379
  name: 'Calidris ferruginea'
}
item {
  id: 380
  name: 'Calidris melanotos'
}
item {
  id: 381
  name: 'Limnodromus griseus'
}
item {
  id: 382
  name: 'Malurus cyaneus'
}
item {
  id: 383
  name: 'Tringa nebularia'
}
item {
  id: 384
  name: 'Todiramphus sanctus vagans'
}
item {
  id: 385
  name: 'Tringa ochropus'
}
item {
  id: 386
  name: 'Tringa glareola'
}
item {
  id: 387
  name: 'Tringa melanoleuca'
}
item {
  id: 388
  name: 'Tringa flavipes'
}
item {
  id: 389
  name: 'Numenius arquata'
}
item {
  id: 390
  name: 'Numenius phaeopus'
}
item {
  id: 391
  name: 'Phalacrocorax carbo novaehollandiae'
}
item {
  id: 392
  name: 'Petroica macrocephala macrocephala'
}
item {
  id: 393
  name: 'Petroica australis longipes'
}
item {
  id: 394
  name: 'Prosthemadera novaeseelandiae novaeseelandiae'
}
item {
  id: 395
  name: 'Asio flammeus'
}
item {
  id: 396
  name: 'Rhipidura fuliginosa fuliginosa'
}
item {
  id: 397
  name: 'Scolopax minor'
}
item {
  id: 398
  name: 'Arenaria interpres'
}
item {
  id: 399
  name: 'Arenaria melanocephala'
}
item {
  id: 400
  name: 'Rhipidura fuliginosa placabilis'
}
item {
  id: 401
  name: 'Limosa limosa'
}
item {
  id: 402
  name: 'Limosa haemastica'
}
item {
  id: 403
  name: 'Limosa fedoa'
}
item {
  id: 404
  name: 'Phalaropus lobatus'
}
item {
  id: 405
  name: 'Bartramia longicauda'
}
item {
  id: 406
  name: 'Limosa lapponica'
}
item {
  id: 407
  name: 'Aegolius acadicus'
}
item {
  id: 408
  name: 'Actitis hypoleucos'
}
item {
  id: 409
  name: 'Trichoglossus haematodus'
}
item {
  id: 410
  name: 'Surnia ulula'
}
item {
  id: 411
  name: 'Polioptila caerulea'
}
item {
  id: 412
  name: 'Spizella passerina'
}
item {
  id: 413
  name: 'Pycnonotus jocosus'
}
item {
  id: 414
  name: 'Passerina cyanea'
}
item {
  id: 415
  name: 'Passerina versicolor'
}
item {
  id: 416
  name: 'Manorina melanocephala'
}
item {
  id: 417
  name: 'Ocyphaps lophotes'
}
item {
  id: 418
  name: 'Jabiru mycteria'
}
item {
  id: 419
  name: 'Pycnonotus cafer'
}
item {
  id: 420
  name: 'Anser cygnoides domesticus'
}
item {
  id: 421
  name: 'Picus viridis'
}
item {
  id: 422
  name: 'Phoebastria nigripes'
}
item {
  id: 423
  name: 'Struthio camelus'
}
item {
  id: 424
  name: 'Phoebastria immutabilis'
}
item {
  id: 425
  name: 'Fulmarus glacialis'
}
item {
  id: 426
  name: 'Francolinus pondicerianus'
}
item {
  id: 427
  name: 'Cynanthus latirostris'
}
item {
  id: 428
  name: 'Podiceps nigricollis'
}
item {
  id: 429
  name: 'Podiceps cristatus'
}
item {
  id: 430
  name: 'Podiceps auritus'
}
item {
  id: 431
  name: 'Dendrocopos major'
}
item {
  id: 432
  name: 'Podiceps grisegena'
}
item {
  id: 433
  name: 'Tachybaptus ruficollis'
}
item {
  id: 434
  name: 'Charadrius montanus'
}
item {
  id: 435
  name: 'Phalacrocorax auritus'
}
item {
  id: 436
  name: 'Phalacrocorax carbo'
}
item {
  id: 437
  name: 'Phalacrocorax penicillatus'
}
item {
  id: 438
  name: 'Aechmophorus clarkii'
}
item {
  id: 439
  name: 'Pelecanus onocrotalus'
}
item {
  id: 440
  name: 'Pelecanus erythrorhynchos'
}
item {
  id: 441
  name: 'Zenaida macroura'
}
item {
  id: 442
  name: 'Vanellus miles'
}
item {
  id: 443
  name: 'Larus occidentalis'
}
item {
  id: 444
  name: 'Trogon massena'
}
item {
  id: 445
  name: 'Larus thayeri'
}
item {
  id: 446
  name: 'Larus heermanni'
}
item {
  id: 447
  name: 'Larus livens'
}
item {
  id: 448
  name: 'Larus canus'
}
item {
  id: 449
  name: 'Larus glaucoides'
}
item {
  id: 450
  name: 'Larus delawarensis'
}
item {
  id: 451
  name: 'Trogon collaris'
}
item {
  id: 452
  name: 'Zenaida asiatica'
}
item {
  id: 453
  name: 'Larus fuscus'
}
item {
  id: 454
  name: 'Larus californicus'
}
item {
  id: 455
  name: 'Prosthemadera novaeseelandiae'
}
item {
  id: 456
  name: 'Trogon elegans'
}
item {
  id: 457
  name: 'Larus glaucescens'
}
item {
  id: 458
  name: 'Trogon citreolus'
}
item {
  id: 459
  name: 'Cepphus columba'
}
item {
  id: 460
  name: 'Himantopus leucocephalus'
}
item {
  id: 461
  name: 'Cepphus grylle'
}
item {
  id: 462
  name: 'Anthornis melanura'
}
item {
  id: 463
  name: 'Leptoptilos crumenifer'
}
item {
  id: 464
  name: 'Threskiornis moluccus'
}
item {
  id: 465
  name: 'Thraupis episcopus'
}
item {
  id: 466
  name: 'Geranoaetus albicaudatus'
}
item {
  id: 467
  name: 'Sterna paradisaea'
}
item {
  id: 468
  name: 'Sterna hirundo'
}
item {
  id: 469
  name: 'Sterna forsteri'
}
item {
  id: 470
  name: 'Lanius excubitor'
}
item {
  id: 471
  name: 'Pharomachrus mocinno'
}
item {
  id: 472
  name: 'Sterna striata'
}
item {
  id: 473
  name: 'Stercorarius parasiticus'
}
item {
  id: 474
  name: 'Stercorarius pomarinus'
}
item {
  id: 475
  name: 'Anas gracilis'
}
item {
  id: 476
  name: 'Rissa tridactyla'
}
item {
  id: 477
  name: 'Rynchops niger'
}
item {
  id: 478
  name: 'Alca torda'
}
item {
  id: 479
  name: 'Fratercula arctica'
}
item {
  id: 480
  name: 'Fratercula cirrhata'
}
item {
  id: 481
  name: 'Turdus merula'
}
item {
  id: 482
  name: 'Turdus plumbeus'
}
item {
  id: 483
  name: 'Turdus grayi'
}
item {
  id: 484
  name: 'Turdus migratorius'
}
item {
  id: 485
  name: 'Turdus viscivorus'
}
item {
  id: 486
  name: 'Cerorhinca monocerata'
}
item {
  id: 487
  name: 'Turdus philomelos'
}
item {
  id: 488
  name: 'Galbula ruficauda'
}
item {
  id: 489
  name: 'Jacana spinosa'
}
item {
  id: 490
  name: 'Saxicola rubicola'
}
item {
  id: 491
  name: 'Upupa epops'
}
item {
  id: 492
  name: 'Euphagus carolinus'
}
item {
  id: 493
  name: 'Gavia pacifica'
}
item {
  id: 494
  name: 'Mimus gilvus'
}
item {
  id: 495
  name: 'Passer italiae'
}
item {
  id: 496
  name: 'Gavia immer'
}
item {
  id: 497
  name: 'Gavia stellata'
}
item {
  id: 498
  name: 'Oenanthe oenanthe'
}
item {
  id: 499
  name: 'Fregata magnificens'
}
item {
  id: 500
  name: 'Fregata minor'
}
item {
  id: 501
  name: 'Falco subbuteo'
}
item {
  id: 502
  name: 'Falco mexicanus'
}
item {
  id: 503
  name: 'Falco femoralis'
}
item {
  id: 504
  name: 'Falco peregrinus'
}
item {
  id: 505
  name: 'Falco rufigularis'
}
item {
  id: 506
  name: 'Falco sparverius'
}
item {
  id: 507
  name: 'Strix varia'
}
item {
  id: 508
  name: 'Falco columbarius'
}
item {
  id: 509
  name: 'Gallinula chloropus'
}
item {
  id: 510
  name: 'Cardellina pusilla'
}
item {
  id: 511
  name: 'Catharus ustulatus'
}
item {
  id: 512
  name: 'Falco novaeseelandiae'
}
item {
  id: 513
  name: 'Catharus guttatus'
}
item {
  id: 514
  name: 'Catharus fuscescens'
}
item {
  id: 515
  name: 'Caracara cheriway'
}
item {
  id: 516
  name: 'Herpetotheres cachinnans'
}
item {
  id: 517
  name: 'Calcarius lapponicus'
}
item {
  id: 518
  name: 'Milvago chimachima'
}
item {
  id: 519
  name: 'Ciconia ciconia'
}
item {
  id: 520
  name: 'Mycteria americana'
}
item {
  id: 521
  name: 'Mycteria ibis'
}
item {
  id: 522
  name: 'Sialia mexicana'
}
item {
  id: 523
  name: 'Ephippiorhynchus senegalensis'
}
item {
  id: 524
  name: 'Cathartes aura'
}
item {
  id: 525
  name: 'Myadestes townsendi'
}
item {
  id: 526
  name: 'Cathartes burrovianus'
}
item {
  id: 527
  name: 'Sarcoramphus papa'
}
item {
  id: 528
  name: 'Coragyps atratus'
}
item {
  id: 529
  name: 'Strix nebulosa'
}
item {
  id: 530
  name: 'Anastomus lamelligerus'
}
item {
  id: 531
  name: 'Pluvialis squatarola'
}
item {
  id: 532
  name: 'Gymnogyps californianus'
}
item {
  id: 533
  name: 'Muscicapa striata'
}
item {
  id: 534
  name: 'Charadrius vociferus'
}
item {
  id: 535
  name: 'Charadrius wilsonia'
}
item {
  id: 536
  name: 'Charadrius melodus'
}
item {
  id: 537
  name: 'Phoenicurus phoenicurus'
}
item {
  id: 538
  name: 'Phoenicurus ochruros'
}
item {
  id: 539
  name: 'Charadrius dubius'
}
item {
  id: 540
  name: 'Eumomota superciliosa'
}
item {
  id: 541
  name: 'Anas querquedula'
}
item {
  id: 542
  name: 'Himantopus mexicanus'
}
item {
  id: 543
  name: 'Haematopus bachmani'
}
item {
  id: 544
  name: 'Pica pica'
}
item {
  id: 545
  name: 'Haematopus ostralegus'
}
item {
  id: 546
  name: 'Haematopus unicolor'
}
item {
  id: 547
  name: 'Vanellus vanellus'
}
item {
  id: 548
  name: 'Vanellus spinosus'
}
item {
  id: 549
  name: 'Vanellus armatus'
}
item {
  id: 550
  name: 'Luscinia svecica'
}
item {
  id: 551
  name: 'Columbina inca'
}
item {
  id: 552
  name: 'Recurvirostra avosetta'
}
item {
  id: 553
  name: 'Phasianus colchicus'
}
item {
  id: 554
  name: 'Pluvialis dominica'
}
item {
  id: 555
  name: 'Cinclus mexicanus'
}
item {
  id: 556
  name: 'Erithacus rubecula'
}
item {
  id: 557
  name: 'Melanerpes aurifrons'
}
item {
  id: 558
  name: 'Charadrius hiaticula'
}
item {
  id: 559
  name: 'Egretta gularis'
}
item {
  id: 560
  name: 'Egretta caerulea'
}
item {
  id: 561
  name: 'Egretta tricolor'
}
item {
  id: 562
  name: 'Egretta thula'
}
item {
  id: 563
  name: 'Egretta garzetta'
}
item {
  id: 564
  name: 'Egretta sacra'
}
item {
  id: 565
  name: 'Monticola solitarius'
}
item {
  id: 566
  name: 'Ardea cocoi'
}
item {
  id: 567
  name: 'Ardea cinerea'
}
item {
  id: 568
  name: 'Ardea herodias'
}
item {
  id: 569
  name: 'Nycticorax nycticorax'
}
item {
  id: 570
  name: 'Turdus rufopalliatus'
}
item {
  id: 571
  name: 'Ardeola ralloides'
}
item {
  id: 572
  name: 'Nyctanassa violacea'
}
item {
  id: 573
  name: 'Aramides cajaneus'
}
item {
  id: 574
  name: 'Bubulcus ibis'
}
item {
  id: 575
  name: 'Butorides virescens'
}
item {
  id: 576
  name: 'Porphyrio martinicus'
}
item {
  id: 577
  name: 'Botaurus lentiginosus'
}
item {
  id: 578
  name: 'Cochlearius cochlearius'
}
item {
  id: 579
  name: 'Anhinga novaehollandiae'
}
item {
  id: 580
  name: 'Anhinga rufa'
}
item {
  id: 581
  name: 'Melozone fusca'
}
item {
  id: 582
  name: 'Aquila chrysaetos'
}
item {
  id: 583
  name: 'Hylocichla mustelina'
}
item {
  id: 584
  name: 'Aphelocoma wollweberi'
}
item {
  id: 585
  name: 'Accipiter striatus'
}
item {
  id: 586
  name: 'Accipiter nisus'
}
item {
  id: 587
  name: 'Accipiter gentilis'
}
item {
  id: 588
  name: 'Egretta rufescens'
}
item {
  id: 589
  name: 'Bucephala clangula'
}
item {
  id: 590
  name: 'Anous stolidus'
}
item {
  id: 591
  name: 'Actitis macularius'
}
item {
  id: 592
  name: 'Ardea purpurea'
}
item {
  id: 593
  name: 'Todiramphus chloris'
}
item {
  id: 594
  name: 'Grus americana'
}
item {
  id: 595
  name: 'Himantopus himantopus'
}
item {
  id: 596
  name: 'Glaucidium gnoma'
}
item {
  id: 597
  name: 'Circus approximans'
}
item {
  id: 598
  name: 'Circus aeruginosus'
}
item {
  id: 599
  name: 'Phalacrocorax sulcirostris'
}
item {
  id: 600
  name: 'Buteo albonotatus'
}
item {
  id: 601
  name: 'Butorides striata'
}
item {
  id: 602
  name: 'Platalea ajaja'
}
item {
  id: 603
  name: 'Buteo brachyurus'
}
item {
  id: 604
  name: 'Ardea alba'
}
item {
  id: 605
  name: 'Buteo swainsoni'
}
item {
  id: 606
  name: 'Alectoris rufa'
}
item {
  id: 607
  name: 'Buteo lineatus'
}
item {
  id: 608
  name: 'Buteo jamaicensis'
}
item {
  id: 609
  name: 'Charadrius nivosus'
}
item {
  id: 610
  name: 'Tringa incana'
}
item {
  id: 611
  name: 'Tringa semipalmata'
}
item {
  id: 612
  name: 'Terathopius ecaudatus'
}
item {
  id: 613
  name: 'Gallinago delicata'
}
item {
  id: 614
  name: 'Buteogallus anthracinus'
}
item {
  id: 615
  name: 'Chroicocephalus philadelphia'
}
item {
  id: 616
  name: 'Circaetus gallicus'
}
item {
  id: 617
  name: 'Chroicocephalus novaehollandiae'
}
item {
  id: 618
  name: 'Chroicocephalus ridibundus'
}
item {
  id: 619
  name: 'Leucophaeus atricilla'
}
item {
  id: 620
  name: 'Leucophaeus pipixcan'
}
item {
  id: 621
  name: 'Onychoprion fuscatus'
}
item {
  id: 622
  name: 'Sternula antillarum'
}
item {
  id: 623
  name: 'Hydroprogne caspia'
}
item {
  id: 624
  name: 'Thalasseus maximus'
}
item {
  id: 625
  name: 'Thalasseus bergii'
}
item {
  id: 626
  name: 'Elanus leucurus'
}
item {
  id: 627
  name: 'Alopochen aegyptiaca'
}
item {
  id: 628
  name: 'Streptopelia senegalensis'
}
item {
  id: 629
  name: 'Gerygone igata'
}
item {
  id: 630
  name: 'Haliaeetus leucocephalus'
}
item {
  id: 631
  name: 'Cistothorus platensis'
}
item {
  id: 632
  name: 'Haliaeetus vocifer'
}
item {
  id: 633
  name: 'Bubo scandiacus'
}
item {
  id: 634
  name: 'Ciccaba virgata'
}
item {
  id: 635
  name: 'Bonasa umbellus'
}
item {
  id: 636
  name: 'Busarellus nigricollis'
}
item {
  id: 637
  name: 'Rostrhamus sociabilis'
}
item {
  id: 638
  name: 'Milvus milvus'
}
item {
  id: 639
  name: 'Gyps fulvus'
}
item {
  id: 640
  name: 'Ficedula hypoleuca'
}
item {
  id: 641
  name: 'Momotus coeruliceps'
}
item {
  id: 642
  name: 'Charadrius semipalmatus'
}
item {
  id: 643
  name: 'Haliastur indus'
}
item {
  id: 644
  name: 'Gyps africanus'
}
item {
  id: 645
  name: 'Ictinia mississippiensis'
}
item {
  id: 646
  name: 'Dives dives'
}
item {
  id: 647
  name: 'Baeolophus atricristatus'
}
item {
  id: 648
  name: 'Baeolophus bicolor'
}
item {
  id: 649
  name: 'Baeolophus inornatus'
}
item {
  id: 650
  name: 'Melospiza melodia'
}
item {
  id: 651
  name: 'Spinus spinus'
}
item {
  id: 652
  name: 'Motacilla alba'
}
item {
  id: 653
  name: 'Certhia americana'
}
item {
  id: 654
  name: 'Bucorvus leadbeateri'
}
item {
  id: 655
  name: 'Anthus pratensis'
}
item {
  id: 656
  name: 'Anthus rubescens'
}
item {
  id: 657
  name: 'Tachycineta albilinea'
}
item {
  id: 658
  name: 'Poecile carolinensis'
}
item {
  id: 659
  name: 'Poecile atricapillus'
}
item {
  id: 660
  name: 'Poecile gambeli'
}
item {
  id: 661
  name: 'Poecile rufescens'
}
item {
  id: 662
  name: 'Periparus ater'
}
item {
  id: 663
  name: 'Chlorophanes spiza'
}
item {
  id: 664
  name: 'Estrilda astrild'
}
item {
  id: 665
  name: 'Cyanistes caeruleus'
}
item {
  id: 666
  name: 'Sphyrapicus varius'
}
item {
  id: 667
  name: 'Petrochelidon pyrrhonota'
}
item {
  id: 668
  name: 'Troglodytes pacificus'
}
item {
  id: 669
  name: 'Troglodytes hiemalis'
}
item {
  id: 670
  name: 'Passer montanus'
}
item {
  id: 671
  name: 'Passer domesticus'
}
item {
  id: 672
  name: 'Aphelocoma californica'
}
item {
  id: 673
  name: 'Amazilia yucatanensis'
}
item {
  id: 674
  name: 'Amazilia tzacatl'
}
item {
  id: 675
  name: 'Dicrurus adsimilis'
}
item {
  id: 676
  name: 'Amazilia violiceps'
}
item {
  id: 677
  name: 'Lonchura punctulata'
}
item {
  id: 678
  name: 'Tigrisoma mexicanum'
}
item {
  id: 679
  name: 'Porphyrio melanotus melanotus'
}
item {
  id: 680
  name: 'Melanitta americana'
}
item {
  id: 681
  name: 'Spizella pallida'
}
item {
  id: 682
  name: 'Amazilia rutila'
}
item {
  id: 683
  name: 'Zenaida aurita'
}
item {
  id: 684
  name: 'Prunella modularis'
}
item {
  id: 685
  name: 'Falco tinnunculus'
}
item {
  id: 686
  name: 'Ixoreus naevius'
}
item {
  id: 687
  name: 'Archilochus colubris'
}
item {
  id: 688
  name: 'Lampornis clemenciae'
}
item {
  id: 689
  name: 'Myiarchus tuberculifer'
}
item {
  id: 690
  name: 'Setophaga ruticilla'
}
item {
  id: 691
  name: 'Myiarchus tyrannulus'
}
item {
  id: 692
  name: 'Zosterops lateralis'
}
item {
  id: 693
  name: 'Zonotrichia leucophrys'
}
item {
  id: 694
  name: 'Agelaius phoeniceus'
}
item {
  id: 695
  name: 'Parus major'
}
item {
  id: 696
  name: 'Zonotrichia capensis'
}
item {
  id: 697
  name: 'Oreothlypis peregrina'
}
item {
  id: 698
  name: 'Oreothlypis celata'
}
item {
  id: 699
  name: 'Oreothlypis ruficapilla'
}
item {
  id: 700
  name: 'Geothlypis philadelphia'
}
item {
  id: 701
  name: 'Geothlypis formosa'
}
item {
  id: 702
  name: 'Setophaga tigrina'
}
item {
  id: 703
  name: 'Setophaga americana'
}
item {
  id: 704
  name: 'Setophaga magnolia'
}
item {
  id: 705
  name: 'Setophaga castanea'
}
item {
  id: 706
  name: 'Setophaga fusca'
}
item {
  id: 707
  name: 'Setophaga petechia'
}
item {
  id: 708
  name: 'Setophaga striata'
}
item {
  id: 709
  name: 'Setophaga palmarum'
}
item {
  id: 710
  name: 'Setophaga pinus'
}
item {
  id: 711
  name: 'Setophaga coronata'
}
item {
  id: 712
  name: 'Setophaga dominica'
}
item {
  id: 713
  name: 'Campylopterus hemileucurus'
}
item {
  id: 714
  name: 'Vireo cassinii'
}
item {
  id: 715
  name: 'Setophaga nigrescens'
}
item {
  id: 716
  name: 'Setophaga townsendi'
}
item {
  id: 717
  name: 'Setophaga occidentalis'
}
item {
  id: 718
  name: 'Setophaga chrysoparia'
}
item {
  id: 719
  name: 'Setophaga virens'
}
item {
  id: 720
  name: 'Cardellina canadensis'
}
item {
  id: 721
  name: 'Cardellina rubra'
}
item {
  id: 722
  name: 'Aphelocoma coerulescens'
}
item {
  id: 723
  name: 'Melanerpes erythrocephalus'
}
item {
  id: 724
  name: 'Emberiza calandra'
}
item {
  id: 725
  name: 'Acanthis flammea'
}
item {
  id: 726
  name: 'Spinus pinus'
}
item {
  id: 727
  name: 'Thraupis abbas'
}
item {
  id: 728
  name: 'Spinus psaltria'
}
item {
  id: 729
  name: 'Spinus lawrencei'
}
item {
  id: 730
  name: 'Spinus tristis'
}
item {
  id: 731
  name: 'Threskiornis aethiopicus'
}
item {
  id: 732
  name: 'Gygis alba'
}
item {
  id: 733
  name: 'Tachycineta bicolor'
}
item {
  id: 734
  name: 'Larus dominicanus dominicanus'
}
item {
  id: 735
  name: 'Lonchura oryzivora'
}
item {
  id: 736
  name: 'Haematopus palliatus'
}
item {
  id: 737
  name: 'Chloris chloris'
}
item {
  id: 738
  name: 'Accipiter cooperii'
}
item {
  id: 739
  name: 'Vireo solitarius'
}
item {
  id: 740
  name: 'Selasphorus platycercus'
}
item {
  id: 741
  name: 'Chroicocephalus scopulinus'
}
item {
  id: 742
  name: 'Aechmophorus occidentalis'
}
item {
  id: 743
  name: 'Hemiphaga novaeseelandiae'
}
item {
  id: 744
  name: 'Xema sabini'
}
item {
  id: 745
  name: 'Ramphastos sulfuratus'
}
item {
  id: 746
  name: 'Dacelo novaeguineae'
}
item {
  id: 747
  name: 'Fulica atra'
}
item {
  id: 748
  name: 'Hirundo rustica erythrogaster'
}
item {
  id: 749
  name: 'Calypte costae'
}
item {
  id: 750
  name: 'Calypte anna'
}
item {
  id: 751
  name: 'Colaptes auratus cafer'
}
item {
  id: 752
  name: 'Sula nebouxii'
}
item {
  id: 753
  name: 'Copsychus saularis'
}
item {
  id: 754
  name: 'Selasphorus sasin'
}
item {
  id: 755
  name: 'Selasphorus rufus'
}
item {
  id: 756
  name: 'Calothorax lucifer'
}
item {
  id: 757
  name: 'Pycnonotus barbatus'
}
item {
  id: 758
  name: 'Larus glaucescens × occidentalis'
}
item {
  id: 759
  name: 'Aphelocoma woodhouseii'
}
item {
  id: 760
  name: 'Florisuga mellivora'
}
item {
  id: 761
  name: 'Haematopus finschi'
}
item {
  id: 762
  name: 'Falcipennis canadensis'
}
item {
  id: 763
  name: 'Archilochus alexandri'
}
item {
  id: 764
  name: 'Circus cyaneus'
}
item {
  id: 765
  name: 'Ardea alba modesta'
}
item {
  id: 766
  name: 'Myiarchus crinitus'
}
item {
  id: 767
  name: 'Buteo regalis'
}
item {
  id: 768
  name: 'Aeronautes saxatalis'
}
item {
  id: 769
  name: 'Chaetura vauxi'
}
item {
  id: 770
  name: 'Chaetura pelagica'
}
item {
  id: 771
  name: 'Setophaga pensylvanica'
}
item {
  id: 772
  name: 'Lanius ludovicianus'
}
item {
  id: 773
  name: 'Anhinga anhinga'
}
item {
  id: 774
  name: 'Acridotheres tristis'
}
item {
  id: 775
  name: 'Sitta pygmaea'
}
item {
  id: 776
  name: 'Actophilornis africanus'
}
item {
  id: 777
  name: 'Sitta canadensis'
}
item {
  id: 778
  name: 'Sitta europaea'
}
item {
  id: 779
  name: 'Sitta pusilla'
}
item {
  id: 780
  name: 'Apus apus'
}
item {
  id: 781
  name: 'Sturnus vulgaris'
}
item {
  id: 782
  name: 'Seiurus aurocapilla'
}
item {
  id: 783
  name: 'Motacilla flava'
}
item {
  id: 784
  name: 'Vireo griseus'
}
item {
  id: 785
  name: 'Toxostoma longirostre'
}
item {
  id: 786
  name: 'Calidris alba'
}
item {
  id: 787
  name: 'Toxostoma redivivum'
}
item {
  id: 788
  name: 'Gallinula galeata'
}
item {
  id: 789
  name: 'Calidris himantopus'
}
item {
  id: 790
  name: 'Eugenes fulgens'
}
item {
  id: 791
  name: 'Icterus wagleri'
}
item {
  id: 792
  name: 'Icterus parisorum'
}
item {
  id: 793
  name: 'Buteo platypterus'
}
item {
  id: 794
  name: 'Gallinago gallinago'
}
item {
  id: 795
  name: 'Icterus spurius'
}
item {
  id: 796
  name: 'Calidris minutilla'
}
item {
  id: 797
  name: 'Dumetella carolinensis'
}
item {
  id: 798
  name: 'Porphyrio hochstetteri'
}
item {
  id: 799
  name: 'Calidris fuscicollis'
}
item {
  id: 800
  name: 'Phalaropus tricolor'
}
item {
  id: 801
  name: 'Colaptes auratus auratus'
}
item {
  id: 802
  name: 'Melanotis caerulescens'
}
item {
  id: 803
  name: 'Tiaris olivaceus'
}
item {
  id: 804
  name: 'Oreoscoptes montanus'
}
item {
  id: 805
  name: 'Limnodromus scolopaceus'
}
item {
  id: 806
  name: 'Tringa solitaria'
}
item {
  id: 807
  name: 'Sitta carolinensis'
}
item {
  id: 808
  name: 'Tringa totanus'
}
item {
  id: 809
  name: 'Dendrocygna autumnalis'
}
item {
  id: 810
  name: 'Dendrocygna viduata'
}
item {
  id: 811
  name: 'Dendrocygna bicolor'
}
item {
  id: 812
  name: 'Icterus abeillei'
}
item {
  id: 813
  name: 'Vanellus chilensis'
}
item {
  id: 814
  name: 'Cygnus buccinator'
}
item {
  id: 815
  name: 'Cygnus cygnus'
}
item {
  id: 816
  name: 'Cygnus columbianus'
}
item {
  id: 817
  name: 'Cygnus olor'
}
item {
  id: 818
  name: 'Icterus galbula'
}
item {
  id: 819
  name: 'Anas platyrhynchos'
}
item {
  id: 820
  name: 'Anas acuta'
}
item {
  id: 821
  name: 'Anas crecca'
}
item {
  id: 822
  name: 'Anas cyanoptera'
}
item {
  id: 823
  name: 'Anas fulvigula'
}
item {
  id: 824
  name: 'Anas discors'
}
item {
  id: 825
  name: 'Anas strepera'
}
item {
  id: 826
  name: 'Anas clypeata'
}
item {
  id: 827
  name: 'Anas chlorotis'
}
item {
  id: 828
  name: 'Rhipidura leucophrys'
}
item {
  id: 829
  name: 'Anas americana'
}
item {
  id: 830
  name: 'Bucephala albeola'
}
item {
  id: 831
  name: 'Mergus serrator'
}
item {
  id: 832
  name: 'Mergus merganser'
}
item {
  id: 833
  name: 'Anser anser'
}
item {
  id: 834
  name: 'Anser albifrons'
}
item {
  id: 835
  name: 'Somateria mollissima'
}
item {
  id: 836
  name: 'Rallus obsoletus'
}
item {
  id: 837
  name: 'Platycercus elegans'
}
item {
  id: 838
  name: 'Melanitta fusca'
}
item {
  id: 839
  name: 'Milvus migrans'
}
item {
  id: 840
  name: 'Gelochelidon nilotica'
}
item {
  id: 841
  name: 'Ninox novaeseelandiae novaeseelandiae'
}
item {
  id: 842
  name: 'Melanitta perspicillata'
}
item {
  id: 843
  name: 'Aythya collaris'
}
item {
  id: 844
  name: 'Aythya ferina'
}
item {
  id: 845
  name: 'Aythya fuligula'
}
item {
  id: 846
  name: 'Numenius americanus'
}
item {
  id: 847
  name: 'Chen caerulescens'
}
item {
  id: 848
  name: 'Chamaea fasciata'
}
item {
  id: 849
  name: 'Branta canadensis'
}
item {
  id: 850
  name: 'Thalasseus elegans'
}
item {
  id: 851
  name: 'Branta sandvicensis'
}
item {
  id: 852
  name: 'Aythya americana'
}
item {
  id: 853
  name: 'Aix sponsa'
}
item {
  id: 854
  name: 'Lophodytes cucullatus'
}
item {
  id: 855
  name: 'Histrionicus histrionicus'
}
item {
  id: 856
  name: 'Aratinga nenday'
}
item {
  id: 857
  name: 'Psittacara holochlorus'
}
item {
  id: 858
  name: 'Cairina moschata'
}
item {
  id: 859
  name: 'Netta rufina'
}
item {
  id: 860
  name: 'Psittacara erythrogenys'
}
item {
  id: 861
  name: 'Sayornis saya'
}
item {
  id: 862
  name: 'Aythya valisineria'
}
item {
  id: 863
  name: 'Picoides albolarvatus'
}
item {
  id: 864
  name: 'Vermivora cyanoptera'
}
item {
  id: 865
  name: 'Corvus caurinus'
}
item {
  id: 866
  name: 'Asio otus'
}
item {
  id: 867
  name: 'Corvus brachyrhynchos'
}
item {
  id: 868
  name: 'Clangula hyemalis'
}
item {
  id: 869
  name: 'Chenonetta jubata'
}
item {
  id: 870
  name: 'Thalasseus sandvicensis'
}
item {
  id: 871
  name: 'Eolophus roseicapilla'
}
item {
  id: 872
  name: 'Colaptes rubiginosus'
}
item {
  id: 873
  name: 'Meleagris gallopavo silvestris'
}
item {
  id: 874
  name: 'Ptiliogonys cinereus'
}
item {
  id: 875
  name: 'Elanoides forficatus'
}
item {
  id: 876
  name: 'Carduelis carduelis'
}
item {
  id: 877
  name: 'Cassiculus melanicterus'
}
item {
  id: 878
  name: 'Dendragapus fuliginosus'
}
item {
  id: 879
  name: 'Psaltriparus minimus'
}
item {
  id: 880
  name: 'Aegithalos caudatus'
}
item {
  id: 881
  name: 'Zosterops lateralis lateralis'
}
item {
  id: 882
  name: 'Haliaeetus leucogaster'
}
item {
  id: 883
  name: 'Uria aalge'
}
item {
  id: 884
  name: 'Tringa semipalmata inornatus'
}
item {
  id: 885
  name: 'Alauda arvensis'
}
item {
  id: 886
  name: 'Galerida cristata'
}
item {
  id: 887
  name: 'Delichon urbicum'
}
item {
  id: 888
  name: 'Helmitheros vermivorum'
}
item {
  id: 889
  name: 'Hylocharis leucotis'
}
item {
  id: 890
  name: 'Mimus polyglottos'
}
item {
  id: 891
  name: 'Gymnorhina tibicen'
}
item {
  id: 892
  name: 'Alcedo atthis'
}
item {
  id: 893
  name: 'Streptopelia chinensis'
}
item {
  id: 894
  name: 'Bombycilla cedrorum'
}
item {
  id: 895
  name: 'Bombycilla garrulus'
}
item {
  id: 896
  name: 'Tadorna tadorna'
}
item {
  id: 897
  name: 'Petroica australis australis'
}
item {
  id: 898
  name: 'Amazona autumnalis'
}
item {
  id: 899
  name: 'Dendragapus obscurus'
}
item {
  id: 900
  name: 'Catherpes mexicanus'
}
item {
  id: 901
  name: 'Tadorna ferruginea'
}
item {
  id: 902
  name: 'Campylorhynchus brunneicapillus'
}
item {
  id: 903
  name: 'Campylorhynchus rufinucha'
}
item {
  id: 904
  name: 'Rhipidura fuliginosa'
}
item {
  id: 905
  name: 'Polioptila melanura'
}
item {
  id: 906
  name: 'Pelecanus occidentalis carolinensis'
}
item {
  id: 907
  name: 'Melozone aberti'
}
item {
  id: 908
  name: 'Melozone crissalis'
}
item {
  id: 909
  name: 'Thryothorus ludovicianus'
}
item {
  id: 910
  name: 'Parabuteo unicinctus'
}
item {
  id: 911
  name: 'Anas platyrhynchos domesticus'
}
item {
  id: 912
  name: 'Troglodytes aedon'
}
item {
  id: 913
  name: 'Buteo lineatus elegans'
}
item {
  id: 914
  name: 'Thamnophilus doliatus'
}
item {
  id: 915
  name: 'Thryomanes bewickii'
}
item {
  id: 916
  name: 'Tadorna variegata'
}
item {
  id: 917
  name: 'Myioborus miniatus'
}
item {
  id: 918
  name: 'Phalacrocorax varius varius'
}
item {
  id: 919
  name: 'Myioborus pictus'
}
item {
  id: 920
  name: 'Larus argentatus smithsonianus'
}
item {
  id: 921
  name: 'Parkesia motacilla'
}
item {
  id: 922
  name: 'Sula granti'
}
item {
  id: 923
  name: 'Ara macao'
}
item {
  id: 924
  name: 'Peucaea ruficauda'
}
item {
  id: 925
  name: 'Calidris subruficollis'
}
item {
  id: 926
  name: 'Phoenicopterus roseus'
}
item {
  id: 927
  name: 'Morus bassanus'
}
item {
  id: 928
  name: 'Pelecanus occidentalis californicus'
}
item {
  id: 929
  name: 'Glaucidium brasilianum'
}
item {
  id: 930
  name: 'Oxyura jamaicensis'
}
item {
  id: 931
  name: 'Myiarchus cinerascens'
}
item {
  id: 932
  name: 'Chloroceryle americana'
}
item {
  id: 933
  name: 'Sturnella neglecta'
}
item {
  id: 934
  name: 'Ramphastos ambiguus'
}
item {
  id: 935
  name: 'Paroaria coronata'
}
item {
  id: 936
  name: 'Buteo buteo'
}
item {
  id: 937
  name: 'Myiodynastes luteiventris'
}
item {
  id: 938
  name: 'Contopus sordidulus'
}
item {
  id: 939
  name: 'Corvus corone'
}
item {
  id: 940
  name: 'Cyanoramphus novaezelandiae'
}
item {
  id: 941
  name: 'Contopus virens'
}
item {
  id: 942
  name: 'Contopus pertinax'
}
item {
  id: 943
  name: 'Contopus cooperi'
}
item {
  id: 944
  name: 'Larus argentatus'
}
item {
  id: 945
  name: 'Halcyon smyrnensis'
}
item {
  id: 946
  name: 'Onychognathus morio'
}
item {
  id: 947
  name: 'Cyanocompsa parellina'
}
item {
  id: 948
  name: 'Cistothorus palustris'
}
item {
  id: 949
  name: 'Tyto alba'
}
item {
  id: 950
  name: 'Trogon caligatus'
}
item {
  id: 951
  name: 'Corvus monedula'
}
item {
  id: 952
  name: 'Corvus ossifragus'
}
item {
  id: 953
  name: 'Spheniscus demersus'
}
item {
  id: 954
  name: 'Corvus frugilegus'
}
item {
  id: 955
  name: 'Corvus splendens'
}
item {
  id: 956
  name: 'Branta bernicla'
}
item {
  id: 957
  name: 'Larus hyperboreus'
}
item {
  id: 958
  name: 'Columba livia domestica'
}
item {
  id: 959
  name: 'Garrulus glandarius'
}
item {
  id: 960
  name: 'Anser anser domesticus'
}
item {
  id: 961
  name: 'Mitrephanes phaeocercus'
}
item {
  id: 962
  name: 'Ardenna creatopus'
}
item {
  id: 963
  name: 'Ardenna gravis'
}
